version: "3.6"

services:
  shion:
    build: .
    container_name: shion-api
    environment:
      PORT: "50051"
      DATABASE_URL: "host=postgres port=5432 user=postgres dbname=postgres password=postgres sslmode=disable"
    expose:
      - 5001
    ports:
      - 5001:5001
      - 9229:9229
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080