# ./Dockerfile.production
FROM golang as builder
WORKDIR /shion
COPY . .
RUN go mod vendor
RUN CGO_ENABLED=0 GOOS=linux go build -a -tags shion -o build/shion ./cmd/api

FROM alpine
COPY --from=builder /shion/build/shion app
ENV PORT 5001
EXPOSE 5001
ENTRYPOINT ["/app"]